title: Aidan DiGregorio
logo: /assets/imgs/headshot.jpg
theme: jekyll-theme-minimal

social_links:
    - title: Lets Connect!
      icon: linkedin
      url: "https://www.linkedin.com/in/aidan-digregorio/"
  
