title: Aidan DiGregorio
logo: /assets/imgs/headshot.jpg
theme: minima

author:
    name: Aidan DiGregorio
    email: aidan.digregorio@gmail.com

minima:
    social_links:
        - title: Lets Connect on LinkedIn
          icon: linkedin
          url: "https://www.linkedin.com/in/aidan-digregorio/"
  
