title: Aidan DiGregorio
logo: /assets/imgs/headshot.jpg
theme: minima

author:
    name: Aidan DiGregorio
    email: aidan.digregorio@gmail.com

github_username: aidandig
linkedin_username: aidan-digregorio
  
